"""Add Manufacturing module

Revision ID: 43960c3c3ffc
Revises: d01491c187b7
Create Date: 2025-11-22 01:17:42.628328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43960c3c3ffc'
down_revision: Union[str, Sequence[str], None] = 'd01491c187b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billofmaterials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billofmaterials_id'), 'billofmaterials', ['id'], unique=False)
    op.create_table('workorder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workorder_id'), 'workorder', ['id'], unique=False)
    op.create_table('bomcomponent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bom_id', sa.Integer(), nullable=False),
    sa.Column('component_product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['bom_id'], ['billofmaterials.id'], ),
    sa.ForeignKeyConstraint(['component_product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bomcomponent_id'), 'bomcomponent', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bomcomponent_id'), table_name='bomcomponent')
    op.drop_table('bomcomponent')
    op.drop_index(op.f('ix_workorder_id'), table_name='workorder')
    op.drop_table('workorder')
    op.drop_index(op.f('ix_billofmaterials_id'), table_name='billofmaterials')
    op.drop_table('billofmaterials')
    # ### end Alembic commands ###
