"""add username to user and rename supply chain product

Revision ID: 6eea3c2a9579
Revises: ca1996a4026b
Create Date: 2025-11-29 07:58:31.929547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eea3c2a9579'
down_revision: Union[str, Sequence[str], None] = 'ca1996a4026b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create new inventory_products table
    op.create_table('inventory_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('cost_price', sa.Float(), nullable=False),
    sa.Column('quantity_in_stock', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_products_id'), 'inventory_products', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_products_name'), 'inventory_products', ['name'], unique=False)
    op.create_index(op.f('ix_inventory_products_sku'), 'inventory_products', ['sku'], unique=True)
    
    # Drop foreign key constraints that reference the old product table
    op.drop_constraint('billofmaterials_product_id_fkey', 'billofmaterials', type_='foreignkey')
    op.drop_constraint('bomcomponent_component_product_id_fkey', 'bomcomponent', type_='foreignkey')
    op.drop_constraint('posorderitem_product_id_fkey', 'posorderitem', type_='foreignkey')
    op.drop_constraint('purchaseorderitem_product_id_fkey', 'purchaseorderitem', type_='foreignkey')
    op.drop_constraint('workorder_product_id_fkey', 'workorder', type_='foreignkey')
    
    # Now drop the old product table
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.drop_index(op.f('ix_product_sku'), table_name='product')
    op.drop_table('product')
    
    # Create new foreign key constraints
    op.create_foreign_key(None, 'billofmaterials', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'bomcomponent', 'products', ['component_product_id'], ['id'])
    op.create_foreign_key(None, 'posorderitem', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'purchaseorderitem', 'inventory_products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'workorder', 'products', ['product_id'], ['id'])
    
    # Add username column (nullable first to allow existing rows)
    op.add_column('user', sa.Column('username', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workorder', type_='foreignkey')
    op.create_foreign_key(op.f('workorder_product_id_fkey'), 'workorder', 'product', ['product_id'], ['id'])
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_column('user', 'username')
    op.drop_constraint(None, 'purchaseorderitem', type_='foreignkey')
    op.create_foreign_key(op.f('purchaseorderitem_product_id_fkey'), 'purchaseorderitem', 'product', ['product_id'], ['id'])
    op.drop_constraint(None, 'posorderitem', type_='foreignkey')
    op.create_foreign_key(op.f('posorderitem_product_id_fkey'), 'posorderitem', 'product', ['product_id'], ['id'])
    op.drop_constraint(None, 'bomcomponent', type_='foreignkey')
    op.create_foreign_key(op.f('bomcomponent_component_product_id_fkey'), 'bomcomponent', 'product', ['component_product_id'], ['id'])
    op.drop_constraint(None, 'billofmaterials', type_='foreignkey')
    op.create_foreign_key(op.f('billofmaterials_product_id_fkey'), 'billofmaterials', 'product', ['product_id'], ['id'])
    op.create_table('product',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('cost_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('quantity_in_stock', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name=op.f('product_supplier_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('product_pkey'))
    )
    op.create_index(op.f('ix_product_sku'), 'product', ['sku'], unique=True)
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=False)
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.drop_index(op.f('ix_inventory_products_sku'), table_name='inventory_products')
    op.drop_index(op.f('ix_inventory_products_name'), table_name='inventory_products')
    op.drop_index(op.f('ix_inventory_products_id'), table_name='inventory_products')
    op.drop_table('inventory_products')
    # ### end Alembic commands ###
