"""add woocommerce settings table

Revision ID: 8a7ef00004e6
Revises: 6eea3c2a9579
Create Date: 2025-11-29 08:23:35.202920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a7ef00004e6'
down_revision: Union[str, Sequence[str], None] = '6eea3c2a9579'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('woocommerce_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_url', sa.String(), nullable=False),
    sa.Column('consumer_key', sa.String(), nullable=False),
    sa.Column('consumer_secret', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_woocommerce_settings_id'), 'woocommerce_settings', ['id'], unique=False)
    
    # Update existing users with null usernames before making column NOT NULL
    op.execute("UPDATE \"user\" SET username = CONCAT('user_', id::text) WHERE username IS NULL")
    
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_woocommerce_settings_id'), table_name='woocommerce_settings')
    op.drop_table('woocommerce_settings')
    # ### end Alembic commands ###
